### ISSUE TITLE
a small problem

### ISSUE THREAD

**Issue by fanxinwen** [TiedNets/TiedNets#1]
Excuse me,I have some question about the 'netw_conf_fpath'  in  'netw_creator_runner.py',I can not find the path '../Simulations/test_2/example_gen_2.ini', I hope you can give me some guidance,best wishes to you!Thank you!

**Comment by AgostinoSturaro** [comment]
Hi and thank you for your interest in our project. Many .ini files, like the one you pointed out, are not included in this project, because they are just local configuration files that we use and change frequently. However, we have are some test configurations you can look at.

In our [project wiki](https://github.com/TiedNets/TiedNets/wiki) you can find a short [user guide page](https://github.com/TiedNets/TiedNets/wiki/User-Guide), which has a couple of example .ini files for the network creator.

What kind of network(s) do you want to create? Do your nodes need to have specific roles?

By the way, the currently maintained branch is "machine-learning". If you want to look at the most recent code, [it's here](https://github.com/TiedNets/TiedNets/tree/machine-learning). The new network_creator has more options too. Just let me know what you need.

**Comment by fanxinwen** [comment]
Sorry,I can not find examples of .ini fies for the network creator in your project wiki,I do not think the test sets are helpful to running of netw_creator,and I also do not know how to invoke functions 'run' in netw_creator,so if possible,I hope you can give me a configuration file about the generation of networks.

**Comment by AgostinoSturaro** [comment]
Sorry for the delay, I've just noticed your answer.
What kind of networks would you like to create?

To create a configuration file, we need to think about the following details
Kind of power network topology?
Kind of communications network topology?
Kind of interdependencies between the two networks?

**Comment by fanxinwen** [comment]
excuse me,I am a graduate student now in China,so I have more problems to consult you，can you give me a convenient means of contact like wechat,msn,...and so on,My contact e-mail is 425715775@qq.com,I hope you can send me an e-mail about your contact information.Thank you.

**Comment by AgostinoSturaro** [comment]
You can Skype me this weekend, I'm in the Rome timezone. Let me know what day and time you prefer.
My skype name is similar to my GitHub, just name.surname

**Comment by fanxinwen** [comment]
Thank you very much!I have added you as a skype buddy.Maybe we can set the apointment at 16:00 in September 17th.(which is 22:00 for me).

**Comment by fanxinwen** [comment]
Thank you very much!I have added you as a skype buddy.Maybe we can set the apointment at 15:00 in September 17th.(which is 22:00 for me).

**Comment by AgostinoSturaro** [comment]
Alright. Tell me if you prefer at 14:00. Please have a look at the [user guide](https://github.com/TiedNets/TiedNets/wiki/User-Guide) and try to make up your mind.

**Comment by simonesilvestri** [comment]
Agostino, alcuni studenti cercano di approfittarsene della disponibilità. Se pensi le sue domande siano idiote e non ci stia perdendo tempo a provare a capire il codice, non ci perdere tempo neanche tu!

Come va a Roma?

Simone

Sent from my iPhone

On Sep 16, 2017, at 8:00 AM, AgostinoSturaro <notifications@github.com<mailto:notifications@github.com>> wrot


Alright. Tell me if you prefer at 14:00. Please have a look at the user guide<https://github.com/TiedNets/TiedNets/wiki/User-Guide> and try to make up your mind.

**Comment by fanxinwen** [comment]
Yes,I think 14:00 is ok.I have looked at the user guide carefully,I will sort out a small document about my question,I'll try to take up less of your time.Thank you!
